<!-- quote-generator-form.php -->
<?php
global $wpdb;
$current_year = date("Y");
$current_user = null;

if (is_user_logged_in()) {
    $current_user = wp_get_current_user();
}

$history = $wpdb->get_results("SELECT * FROM wp_quote_history WHERE user_id = $current_user->ID ORDER BY quotation_date DESC");

?>
<div class="header-container">
    <h1>TBS Price Quotation Generator <sub><?php echo $current_year; ?></sub></h1>
    <button value="Generate Quote" id="openHistory" class="btn btn-primary">History</button>
</div>

<div id="history_popup" class="popup">
    <div class="popup-content">
        <span class="close">&times;</span>

        <div class="popup-header">
            <h1>Quote History</h1>
            <p>Quote generated by <strong><?php echo esc_html($current_user->display_name ?? ''); ?></strong></p>
        </div>

        <?php if (empty($history)) : ?>
            <p style="text-align:center; padding: 20px; color:#6c757d;">No quote history found.</p>
        <?php else : ?>

            <?php foreach ($history as $quote) : ?>

                <?php
                // -------- Safe decode ----------
                $raw_details = isset($quote->details) ? (string)$quote->details : '';
                $details = json_decode(wp_unslash($raw_details));

                // ถ้า decode ไม่ผ่าน ให้ข้าม (ไม่ให้ warning)
                if (!is_object($details)) {
                    continue;
                }

                // items ต้องเป็น array เสมอ
                $items = (isset($details->items) && is_array($details->items)) ? $details->items : array();

                // running number
                $revision = isset($quote->revision_number) ? (string)$quote->revision_number : '0';
                $running_number = ($revision === '0')
                    ? (string)($quote->running_number ?? '')
                    : (string)($quote->running_number ?? '') . "_R" . $revision;

                // headline fields (default กัน null)
                $client_name  = isset($details->client_name) ? (string)$details->client_name : '';
                $total_amount = isset($details->total_amount) ? (string)$details->total_amount : '';
                $currency     = isset($details->currency) ? (string)$details->currency : '';

                // data-details สำหรับ Import (ใช้ wp_json_encode)
                $json = wp_json_encode($details, JSON_UNESCAPED_UNICODE);
                $safe_b64 = esc_attr(base64_encode($json));
                ?>

                <div class="quote-item">
                    <div class="quote-header" onclick="toggleDetails(this)">
                        <h3 class="quote-title">
                            <?php echo esc_html($running_number); ?> -
                            <?php echo esc_html($client_name); ?> -
                            <?php echo esc_html(trim($total_amount . ' ' . $currency)); ?>
                        </h3>

                        <button type="button"
                            class="quote-button import-quote-btn"
                            data-details-b64="<?php echo $safe_b64; ?>">
                            Import
                        </button>
                    </div>

                    <div class="quote-details" style="display:none;">

                        <?php
                        // -------- Unique services ----------
                        $unique_services = array();
                        if (!empty($items)) {
                            foreach ($items as $service) {
                                $svc_name = isset($service->service_name) ? trim((string)$service->service_name) : '';
                                if ($svc_name !== '' && !in_array($svc_name, $unique_services, true)) {
                                    $unique_services[] = $svc_name;
                                }
                            }
                        }

                        if (!empty($unique_services)) : ?>
                            <div class="services-used"
                                style="margin-bottom:15px; padding:10px 15px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius:8px; color:#fff; box-shadow:0 2px 4px rgba(0,0,0,0.1);">
                                <strong style="font-weight:600;">Services Used:</strong>
                                <?php echo esc_html(implode(', ', $unique_services)); ?>
                            </div>
                        <?php endif; ?>

                        <div class="details-grid">
                            <div class="details-column">
                                <ul>
                                    <li>Quotation Valid Date: <?php echo esc_html($details->quotation_valid_date ?? ''); ?></li>
                                    <li>Client Name: <?php echo esc_html($details->client_name ?? ''); ?></li>
                                    <li>Client Address: <?php echo esc_html($details->client_address ?? ''); ?></li>
                                    <li>Client Email: <?php echo esc_html($details->client_email ?? ''); ?></li>
                                    <li>Client Phone: <?php echo esc_html($details->client_phone ?? ''); ?></li>
                                    <li>Project Description: <?php echo esc_html($details->project_desc ?? ''); ?></li>
                                    <li>Company Name: <?php echo esc_html($details->company_name ?? ''); ?></li>
                                    <li>Full Name: <?php echo esc_html($details->full_name ?? ''); ?></li>
                                    <li>Company Address: <?php echo esc_html($details->company_address ?? ''); ?></li>
                                    <li>Company Email: <?php echo esc_html($details->company_email ?? ''); ?></li>
                                    <li>Company Phone: <?php echo esc_html($details->company_phone ?? ''); ?></li>
                                </ul>
                            </div>

                            <div class="details-column">
                                <ul>
                                    <li>Customer Tax ID: <?php echo esc_html($details->customer_tax_id ?? ''); ?></li>
                                    <?php $remark = str_replace('rn', "\n", (string)($details->remark ?? '')); ?>
                                    <li>Remark:<br><?php echo nl2br(esc_html($remark)); ?></li>
                                    <li>Discount Type: <?php echo esc_html($details->discount_type ?? ''); ?></li>
                                    <li>Discount: <?php echo esc_html($details->discount ?? ''); ?></li>
                                    <li>VAT Percentage: <?php echo esc_html($details->vat_percentage ?? ''); ?></li>
                                    <li>Currency: <?php echo esc_html($details->currency ?? ''); ?></li>
                                    <li>Total Amount: <?php echo esc_html($details->total_amount ?? ''); ?></li>
                                    <li>Discount Sub Total: <?php echo esc_html($details->discount_sub_total ?? ''); ?></li>
                                    <li>VAT Amount: <?php echo esc_html($details->vat_amount ?? ''); ?></li>
                                    <li>Total Amount with VAT: <?php echo esc_html($details->total_amount_with_vat ?? ''); ?></li>
                                </ul>
                            </div>
                        </div>

                        <?php
                        // -------- Group items by group_id ----------
                        $grouped_items = array();
                        if (!empty($items)) {
                            foreach ($items as $service) {
                                $group_id = isset($service->group_id) ? (string)$service->group_id : 'ungrouped';
                                if (!isset($grouped_items[$group_id])) {
                                    $grouped_items[$group_id] = array();
                                }
                                $grouped_items[$group_id][] = $service;
                            }
                        }

                        // service_group_name จาก details (ให้เป็น array)
                        $service_group_names = array();
                        if (isset($details->service_group_name)) {
                            $service_group_names = (array)$details->service_group_name;
                        }

                        if (!empty($grouped_items)) :
                            foreach ($grouped_items as $group_id => $group_services) {

                                // หา service_name
                                $service_name = '';
                                if (isset($service_group_names[$group_id]) && $service_group_names[$group_id] !== '') {
                                    $service_name = (string)$service_group_names[$group_id];
                                } else {
                                    foreach ($group_services as $svc) {
                                        if (!empty($svc->service_name)) {
                                            $service_name = (string)$svc->service_name;
                                            break;
                                        }
                                    }
                                }
                                if ($service_name === '') {
                                    $service_name = 'General Services';
                                }

                                // group total
                                $group_total = 0.0;
                                foreach ($group_services as $svc) {
                                    $group_total += isset($svc->total_price) ? (float)$svc->total_price : 0.0;
                                }
                        ?>

                                <div style="margin-bottom:25px;">
                                    <h4 style="background:#3C3D3A; color:#fff; padding:10px; margin:0; border-radius:5px 5px 0 0;">
                                        Service: <?php echo esc_html($service_name); ?>
                                    </h4>

                                    <table class="table table-striped" style="margin-bottom:0; border:1px solid #dee2e6;">
                                        <thead style="background-color:#f8f9fa;">
                                            <tr>
                                                <th>#</th>
                                                <th>Description</th>
                                                <th>Qty</th>
                                                <th>Unit Price</th>
                                                <th>Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            $row_counter = 1;
                                            foreach ($group_services as $service) {

                                                $row_id = isset($service->row_id) ? (string)$service->row_id : '';
                                                $is_parent = (strpos($row_id, '.') === false);
                                                $display_id = $is_parent ? $row_counter++ : $row_id;

                                                $desc  = isset($service->description) ? (string)$service->description : '';
                                                $desc  = esc_html(wp_unslash($desc));

                                                $qty   = isset($service->quantity) ? esc_html((string)$service->quantity) : '0';
                                                $price = isset($service->price) ? number_format((float)$service->price, 2) : '0.00';
                                                $total = isset($service->total_price) ? number_format((float)$service->total_price, 2) : '0.00';

                                                $font_weight = $is_parent ? 'font-weight:bold;' : '';
                                            ?>
                                                <tr>
                                                    <td style="<?php echo esc_attr($font_weight); ?>"><?php echo esc_html($display_id); ?></td>
                                                    <td><?php echo $desc; ?></td>
                                                    <td><?php echo $qty; ?></td>
                                                    <td><?php echo esc_html($price); ?></td>
                                                    <td><?php echo esc_html($total); ?></td>
                                                </tr>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>

                            <?php } // end foreach groups
                        else : ?>
                            <p style="text-align:center; padding:20px; color:#6c757d;">No services found in this quote.</p>
                        <?php endif; ?>

                    </div><!-- /.quote-details -->
                </div><!-- /.quote-item -->

            <?php endforeach; ?>

        <?php endif; ?>
    </div>
</div>



<form id="price_quotation_form" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"
    target="_blank" class="container mt-4">
    <input type="hidden" name="action" value="process_quote_form">

    <!-- Currency Selection -->
    <div class="form-group">
        <label for="currencySwitch" class="form-label">Select Currency:</label>
        <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="radio" id="thbCurrency" name="currency" value="THB" checked>
            <label class="form-check-label" for="thbCurrency">THB</label>
        </div>
        <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="radio" id="usdCurrency" name="currency" value="USD">
            <label class="form-check-label" for="usdCurrency">USD</label>
        </div>
        <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="radio" id="gbpCurrency" name="currency" value="GBP">
            <label class="form-check-label" for="gbpCurrency">GBP</label>
        </div>
        <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="radio" id="sgdCurrency" name="currency" value="SGD">
            <label class="form-check-label" for="sgdCurrency">SGD</label>
        </div>
        <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="radio" id="eurCurrency" name="currency" value="EUR">
            <label class="form-check-label" for="eurCurrency">EUR</label>
        </div>
    </div>


    <!-- Logo section -->
    <h3>General Information</h3>
    <div class="row">
        <div class="col-md-6">
            <!-- Quotation Date -->
            <div class="form-group">
                <label for="quotation_date">Date Created:</label>
                <input type="date" id="quotation_date" name="quotation_date" class="form-control">
            </div>
        </div>
        <div class="col-md-6">
            <!-- Quotation Valid Until Date -->
            <div class="form-group">
                <label for="quotation_valid_date">Valid Until Date:</label>
                <input type="date" id="quotation_valid_date" name="quotation_valid_date" class="form-control">
            </div>
        </div>
    </div>

    <!-- Project Description -->
    <div class="form-group">
        <label for="project_desc" class="sr-only">Quote/Project Description:</label>
        <textarea name="project_desc" id="project_desc" class="form-control" rows="5"
            placeholder="Enter Quote/Project Description"></textarea>
        <span style="font-size: 14px;">‣ Copy Paste ( • ○ ) for bullet points.</span>
    </div>

    <!-- Team Member  -->
    <div class="row">
        <div class="col-md-6">
            <label for="revised_quotation" class="form-label">Is this a revised quotation?</label>
            <select name="revised_quotation" id="revised_quotation" class="form-select">
                <option value="false" selected>No</option>
                <option value="true">Yes</option>
            </select>
            <input type="hidden" name="running_number" id="running_number">

        </div>
        <div class="col-md-4">
            <label for="team_dropdown" class="form-label">Select your Name to Autofill Information</label>
            <select id="team_dropdown" class="form-select" style="margin-bottom:20px;">
            </select>
        </div>
    </div>

    <!-- Company Information and Quotation To side by side -->
    <div class="row">
        <div class="col-md-6">
            <h3>Client Information</h3>
            <div class="form-group">
                <label class="sr-only" for="client_name">Client Company Name:</label>
                <input type="text" id="client_name" name="client_name" placeholder="Enter client company name" class="form-control">
            </div>
            <!-- Customer Tax ID -->
            <div class="form-group">
                <label class="sr-only" for="customer_tax_id">Valid Until Date:</label>
                <input type="text" id="customer_tax_id" name="customer_tax_id" placeholder="Customer Tax ID" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="client_address">Address:</label>
                <input type="text" id="client_address" name="client_address" placeholder="Enter client address" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="client_email">Email:</label>
                <input type="email" id="client_email" name="client_email" placeholder="Enter client email" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="client_phone">Phone:</label>
                <input type="tel" id="client_phone" name="client_phone" placeholder="Enter client phone" class="form-control">
            </div>
        </div>
        <div class="col-md-6">
            <h3>Our Information</h3>
            <div class="form-group">
                <label class="sr-only" for="company_name">Company Name:</label>
                <input type="text" id="company_name" name="company_name" value="The Business SEO Co., Ltd (Trading as TBS Marketing)"
                    placeholder="Enter company name" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="full_name">Your Full Name:</label>
                <input type="text" id="full_name" id="full_name" name="full_name" placeholder="Enter Full name" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="company_address">Address:</label>
                <input type="text" id="company_address" name="company_address"
                    value="1023, 4th Floor TPS Building Pattanakarn Road, Suanluang, Bangkok, Thailand, 10250"
                    placeholder="Enter company address" class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="company_email">Email:</label>
                <input type="email" id="company_email" name="company_email" placeholder="Enter your company email"
                    class="form-control">
            </div>
            <div class="form-group">
                <label class="sr-only" for="company_phone">Phone:</label>
                <input type="tel" id="company_phone" name="company_phone" placeholder="Enter your company mobile"
                    class="form-control">
            </div>
        </div>
    </div>

    <!-- Items: Service Groups -->
    <h3>Services</h3>
    <div class="col-md-7">
        <div class="form-group">
            <label for="column_to_print" class="form-label">Select column to print:</label>
            <div class="form-check form-switch form-check-inline">
                <input class="form-check-input" type="checkbox" id="service_dropdown" name="column_to_print[]" value="Qty"
                    checked>
                <label class="form-check-label" for="qtyColumn">Qty</label>
            </div>
            <div class="form-check form-switch form-check-inline">
                <input class="form-check-input" type="checkbox" id="rateColumn" name="column_to_print[]"
                    value="Rate" checked>
                <label class="form-check-label" for="rateColumn">Rate</label>
            </div>
            <div class="form-check form-switch form-check-inline">
                <input class="form-check-input" type="checkbox" id="Quotation-number" name="column_to_print[]" value="Quotation-number" checked>
                <label class="form-check-label" for="Quotation-number">Quotation number</label>

            </div>
        </div>
    </div>

    <div id="service_groups_container">
        <!-- Service groups will be dynamically added here by JS. Each group contains its own dropdown, table and controls. -->
    </div>

    <div class="row" style="margin-top:10px;">
        <div class="col-md-12">
            <button type="button" id="add_service_group" class="btn btn-outline-primary">Add new Service</button>
            <p style="margin-top:8px; font-size:0.9em; color:#555;"></p>
        </div>
    </div>

    <div class="row">
        <!-- Remark -->
        <div class="col-md-6">
            <label for="remark" class="sr-only">Remark:</label>
            <textarea name="remark" id="remark" class="form-control" rows="10"
                placeholder="Enter any remarks here"></textarea>
            <span style="font-size: 14px;">‣ Copy Paste ( • ○ ) for bullet points.</span>
        </div>
        <!-- Prices -->
        <div class="col-md-6">
            <!-- Total Amount -->
            <div class="form-group">
                <p for="total_amount">Total Amount (excluding VAT) - <span id="total_amount_label"
                        class="font-weight-bold">0.00 THB</span></p>

                <input type="text" id="total_amount_input" name="total_amount_without_vat_and_discount" class="font-weight-bold d-none" value="0.00" readonly>
            </div>

            <!-- Discount Type -->
            <div class="form-group row">
                <label for="discount_type" class="col-sm-3 col-form-label">Discount Type:</label>
                <div class="col-sm-9">
                    <select name="discount_type" id="discount_type" class="form-control">
                        <option value="percentage">Percentage (%)</option>
                        <option value="fixed">Fixed Amount (THB)</option>
                    </select>
                </div>
            </div>

            <!-- Discount -->
            <div class="form-group row">
                <label for="discount" class="col-sm-3 col-form-label">Discount:</label>
                <div class="col-sm-9">
                    <input type="number" name="discount" id="discount" value="0" class="form-control" min="0"
                        step="0.01">
                </div>
            </div>

            <!-- VAT Percentage -->
            <div class="form-group row">
                <label for="vat_percentage" class="col-sm-3 col-form-label">VAT %:</label>
                <div class="col-sm-9">
                    <input type="number" name="vat_percentage" id="vat_percentage" class="form-control" value="7"
                        min="0" max="100" step="1">
                </div>
            </div>

            <!-- VAT Amount -->
            <div class="form-group">
                <p for="vat_amount">VAT Amount - <span id="vat_amount_label" class="font-weight-bold">0.00 THB</span>
                </p>
                <!-- <label for="vat_amount">VAT Amount - </label> -->
                <input type="text" id="vat_amount_input" name="total_vat_amount" class="font-weight-bold d-none" value="0.00" readonly>

            </div>

            <!-- Total Amount with VAT -->
            <div class="form-group">
                <p for="total_amount_with_vat">
                    Total Amount (including VAT) -
                    <span id="total_amount_with_vat_label" class="font-weight-bold">0.00 THB</span>

                    <input
                        type="number"
                        id="month_number_input"
                        min="1"
                        max="12"
                        value="1"
                        style="display: none; width: 60px; padding: 2px 5px; font-size: 0.9em; margin-left: 5px; vertical-align: middle;" />

                    <select id="monthly_price"
                        style="display: none; width: auto; min-width: 90px; padding: 2px 5px; margin-left: 5px; font-size: 0.9em; vertical-align: middle;">
                        <option value="Month">/ Month</option>
                        <option value="Year">/ Year</option>
                    </select>
                </p>

                <input type="text" id="total_amount_with_vat_input" name="total_amount_with_vat" class="font-weight-bold d-none" value="0.00" readonly>
                <input type="hidden" name="monthly_price_input" id="monthly_price_input" value="1 Month">
            </div>


        </div>
    </div>

    <!-- Submit Button -->
    <button type="submit" value="Generate Quote" class="btn btn-success">Generate Quote</button>
</form>